### ISSUE TITLE
adding play button at the end of file name

### ISSUE THREAD

**Issue by iamspa** [SanokKule/min-media-player#1]
your plugins is really good.
but can you adding play button at the end of file name like IlyaBOT video-player?
because with this button, we can play directly without click the file and choose what to play
![image](https://github.com/user-attachments/assets/1b345b57-3ced-431d-855b-bc1ed09baadd)

**Comment by SanokKule** [comment]
That's the default, are you sure you didn't enable this option?
![Screenshot_2024-10-15-22-36-25-339_com chrome beta](https://github.com/user-attachments/assets/00c920d3-2c3f-4128-aa92-ebfd985389c0)

**Comment by iamspa** [comment]
> That's the default, are you sure you didn't enable this option? ![Screenshot_2024-10-15-22-36-25-339_com chrome beta](https://private-user-images.githubusercontent.com/24497821/376745162-00c920d3-2c3f-4128-aa92-ebfd985389c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTk0MjQsIm5iZiI6MTcyOTAxOTEyNCwicGF0aCI6Ii8yNDQ5NzgyMS8zNzY3NDUxNjItMDBjOTIwZDMtMmMzZi00MTI4LWFhOTItZWJmZDk4NTM4OWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE5MDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NzA5NmJiNTU4MGY4NWNjMjE2NGY5MzQ1NmE5ZmIxMDA1MGMwNjU3ODc2ZjAzNWM4MjQ1OWFhNTgzYTRiZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7YRDxzcv8KtE1MJ8xXLbjCR-FphWCxMz2KyH-NLMkqc)

i already enable that option, but the play button still doesnt show at the file menu
BTW iam using lastest version of hfs
![image](https://github.com/user-attachments/assets/ad04e73c-4399-4f09-bf3c-87d06760010c)

**Comment by SanokKule** [comment]
I'm guessing you want a button in both places, since there was a bug in previous versions which made both appear if you selected that option.
File menu and the file list are different things.

**Comment by iamspa** [comment]
![image](https://github.com/user-attachments/assets/4313cbb1-2159-4a3e-8072-77b16e35a661)
move play buttons in to the file menu only show when we click the file, it is not add play button at the end of the file name.
while IlyaBOT video-player plugins adding play button at the end of file name and it make it simple if we want to watch the video

**Comment by SanokKule** [comment]
Yes, that's the point.

**Comment by SanokKule** [comment]
I added an option to toggle both places, update the plugin

**Comment by iamspa** [comment]
> I added an option to toggle both places, update the plugin

iam already update the plugin and setting like this
![image](https://github.com/user-attachments/assets/3fb53dec-4b92-4144-baaa-6e22754d2f3a)
but the play button on the end of file still dont show
![image](https://github.com/user-attachments/assets/7ba8ebc3-7b3a-4c37-9aed-00efc18d9b3a)
is there because iam using lastest version of hfs?

**Comment by SanokKule** [comment]
Are you on 0.53?

**Comment by iamspa** [comment]
> Are you on 0.53?

yes, iam using 0.53.1

**Comment by SanokKule** [comment]
I see the problem now, give me some time to fix it

**Comment by SanokKule** [comment]
Is it working now?

**Comment by iamspa** [comment]
> I see the problem now, give me some time to fix it

thank you so much sir
i use your plugin because its better, because when using ilyabot video player, when i close the player, it scroll back to the top and must scroll down again to play the file at the bottom

**Comment by iamspa** [comment]
> Is it working now?

yes it is working now thank you, but next problem, when i watch video and make it full screen and exit fullscreen and close the video, its suddenly goes back to the top of file, not remaining in the same position of file

**Comment by SanokKule** [comment]
I'm not sure i can fix that, but open another issue for this please

**Comment by SanokKule** [comment]
> yes it is working now thank you

Nice

**Comment by iamspa** [comment]
> I'm not sure i can fix that, but open another issue for this please

okay
