### ISSUE TITLE
Focus issues

### ISSUE THREAD

**Issue by killersolyom** [SanokKule/min-media-player#3]
If I press the up arrow or if you use the fn + function button on a laptop to increase the volume, the video player gets a white frame.
Unfortunately it happens even in full screen. So my question is, is it possible to make the video player not-focusable? Or at least hide the white border somehow.

![player_focus_bug](https://github.com/user-attachments/assets/d5111db3-a8fe-494c-9e2c-2ce98b9077cb)

**Comment by SanokKule** [comment]
I guess i'll leave focus only on the button for closing then?

**Comment by SanokKule** [comment]
Does this look fine? Update to 1.192

**Comment by killersolyom** [comment]
I will check tomorrow and come back with an answer

**Comment by killersolyom** [comment]
Yes, it also appears on my latest version

**Comment by rejetto** [comment]
css? `outline: 0;`

**Comment by SanokKule** [comment]
Does this 42fa600d2260f9b18b6258bf0039ef3d0d178ddc fix the problem now?

**Comment by killersolyom** [comment]
Thank you @rejetto @SanokKule, this solves the problem. 😄
